config/routes.rb
Rails.application.routes.draw do
  resources :therapists, only: [:index, :show]
  resources :insurances, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "therapists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/insurance.rb
class Insurance < ApplicationRecord
  has_many :insurance_therapists, dependent: :destroy
  has_many :therapists, through: :insurance_therapists
end

app/models/insurance_therapist.rb
class InsuranceTherapist < ApplicationRecord
  belongs_to :insurance
  belongs_to :therapist
end

app/models/therapist.rb
class Therapist < ApplicationRecord
  has_many :insurance_therapists, dependent: :destroy
  has_many :insurances, through: :insurance_therapists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: %i[show]

  # GET /insurances or /insurances.json
  def index
    @pagy, @insurances = pagy(Insurance.all)
  end

  # GET /insurances/1 or /insurances/1.json
  def show
  end

  private

  def set_insurance
    @insurance = Insurance.find(params[:id])
  end
end

app/controllers/therapists_controller.rb
class TherapistsController < ApplicationController
  before_action :set_therapist, only: %i[show]

  # GET /therapists or /therapists.json
  def index
    scope = Therapist.all.includes(:insurances)

    if params[:insurance].present?
      ids = InsuranceTherapist.where(insurance_id: params[:insurance]).pluck(:therapist_id).uniq
      scope = scope.where(id: ids)
    end

    if params[:remote].present?
      scope = scope.where(remote: params[:remote] == "yes")
    end

    if params[:city].present?
      scope = scope.where(city: params[:city])
    end

    logger.debug "scope: #{scope.to_sql}"
    @pagy, @therapists = pagy(scope)
  end

  # GET /therapists/1 or /therapists/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_therapist
    @therapist = Therapist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/views/insurances/_insurance.html.erb
<div id="<%= dom_id insurance %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= insurance.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this insurance", insurance, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/insurances/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Insurances</h1>
  </div>

  <div id="therapists" class="min-w-full flex flex-col gap-8">
    <%= render @insurances %>
  </div>

  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/insurances/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @insurance %>

    <%= link_to "Back to insurances", insurances_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JourneyClinical</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="flex flex-row justify-between gap-8 my-8 mx-4">
      <h1 class="font-medium text-lg">
        <%= link_to "Journey Clinical", root_path %>
      </h1>
      <div class="flex flex-row gap-3">
        <%= link_to "Therapists", therapists_path %>
        <%= link_to "Insurances", insurances_path %>
      </div>
    </nav>
    <main class="container mx-auto mt-20 mb-16 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/therapists/_therapist.html.erb
<div id="<%= dom_id therapist %>" class="flex flex-col gap-3 border rounded-lg shadow p-4">
    <p class="flex flex-row justify-between">
      <strong class="block font-medium mb-1"><%= therapist.name %></strong>
      
      <span>
        Remote? <%= therapist.remote ? "Yes" : "No" %>
      </span>
    </p>

    <p class="">
      <strong class="block font-medium mb-1">Address:</strong>
      <%= therapist.street %>
      <br>
      <% if therapist.street_2.present? %>
        <%= therapist.street_2 %>
        <br>
      <% end %>
      <%= therapist.city %>, <%= therapist.state %> <%= therapist.zip %>
    </p>

    <p class="">
      <strong class="block font-medium mb-1">Insurance:</strong>
      <%= therapist.insurances.pluck(:name).join(", ") %>
    </p>

    <% if action_name != "show" %>
    <div>
      <%= link_to "Show this therapist", therapist, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
    <% end %>
</div>

app/views/therapists/index.html.erb
<div class="w-full flex flex-col gap-8">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Therapists</h1>
  </div>

  <form>
    <div class="flex flex-row gap-4 justify-start items-end" data-turbo-cache="false">
      <div class="input flex flex-col">
        <label for="insurance">Insurance</label>
        <%= select_tag "insurance", options_from_collection_for_select(Insurance.all, "id", "name", params[:insurance]), include_blank: true %> 
      </div>
      <div class="input flex flex-col">
        <label for="remote">Remote</label>
        <%= select_tag "remote", options_from_collection_for_select([["yes", "Yes"], ["no", "No"]], "first", "second", params[:remote]), include_blank: true %> 
      </div>
      <div class="input flex flex-col">
        <label for="city">City</label>
        <%= select_tag "city", options_for_select(Constants::CITIES, params[:city]), include_blank: true %> 
      </div>
      <div class="">
        <%= submit_tag "Filter", class: "rounded-lg py-2 px-5 bg-blue-600 text-white block font-medium" %>
      </div>
    </div>
  </form>

  <% if @therapists.empty? %>
    <div class="py-24">
      No therapists found
    </div>
  <% else %>
    <div>
      Found <%= pluralize(@pagy.count, "therapist") %>
    </div>

    <div id="therapists" class="min-w-full flex flex-col gap-8">
      <%= render @therapists %>
    </div>

    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  <% end %>
</div>

app/views/therapists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @therapist %>

    <%= link_to "Back to therapists", therapists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>